;WITH CTE AS (

SELECT MONTH(DATE) DATE,SUM(Amount) TotalAmt,COUNT(1) AS CNT,
CASE WHEN -1*SUM(Amount)  > = 100 AND COUNT(1) > = 3 THEN 5 ELSE 0 END AS AmountNeedstoDeduct
FROM TRANSACTIONS
WHERE Amount < 0
GROUP BY MONTH(DATE)
)
SELECT (SELECT SUM(Amount) FROM TRANSACTIONS)-(60-SUM(AmountNeedstoDeduct))
FROM CTE 
