;WITH CTE AS (
SELECT 1 AS N,5 AS Ded

UNION ALL 

SELECT N+1,5 AS Ded 
FROM CTE 
WHERE N<=11
),CTE_1 AS (
SELECT *,CASE WHEN T.TotalAmt > = -100 AND CNT > = 3 THEN -5 ELSE 0 END AS AmountNeedstoDeduct 
FROM (
SELECT MONTH(DATE) DATE,SUM(Amount) TotalAmt,COUNT(1) AS CNT
FROM TRANSACTIONS
WHERE Amount < 0
GROUP BY MONTH(DATE)
)T
)
SELECT (SELECT SUM(Amount) FROM TRANSACTIONS)-SUM(C.Ded+ISNULL(CC.AmountNeedstoDeduct,0))
FROM CTE C
LEFT JOIN CTE_1 CC 
	ON C.N = CC.DATE
