SELECT I.ITEMID,I.INVETORYITEMID,I.INVENTORYUNITS,O.ORDERID,O.UNITSELIGIBLETOORDER,(UNITSELIGIBLETOORDER-INVENTORYUNITS) AS REMAININGUNITS
INTO #TEMP
FROM INVENTORY I
INNER JOIN INVORDERS O
	ON O.ITEMID = I.ITEMID
ORDER BY I.ITEMID,I.INVENTORYUNITS

SELECT *,LAG(REMAININGUNITS) OVER (PARTITION BY ITEMID ORDER BY INVENTORYUNITS),
(LAG(REMAININGUNITS) OVER (PARTITION BY ITEMID ORDER BY INVENTORYUNITS)-INVENTORYUNITS) FROM #TEMP



SELECT *,(LAG(REMAININGUNITS) OVER (PARTITION BY ITEMID ORDER BY INVENTORYUNITS)-INVENTORYUNITS) AS REMAININGUNITS FROM #TEMP

UPDATE T
	SET T.REMAININGUNITS = (LAG(REMAININGUNITS) OVER (PARTITION BY ITEMID ORDER BY INVENTORYUNITS)-INVENTORYUNITS)
	FROM #TEMP T


	SELECT * FROM #TEMP
	ALTER TABLE #TEMP DROP COLUMN REMAININGUNITS

	SELECT ITEMID,UNITSELIGIBLETOORDER,INVENTORYUNITS,
	UNITSELIGIBLETOORDER-SUM(INVENTORYUNITS) OVER (PARTITION BY ORDER BY ITEMID ROWS UNBOUNDED PRECEDING) AS UNITS
	FROM #TEMP
	ORDER BY ITEMID






